/*
 * windows.h
 *
 * Author:
 *     Owen Patrick, Qt
 *
 * School:
 *     Rochester Institute of Technology
 *
 * Version:
 *     2.0
 *
 * Description:
 *      Class descriptor for the standard window class needed by Qt.
 *      Initally generated by Qt, widgets, signals and slots added in as designed
 *      by author.
 */
#ifndef WINDOW_H
#define WINDOW_H

#include <QtGui>
#include <QWidget>
#include <QtWidgets>


#include "glwidget.h"

QT_BEGIN_NAMESPACE
class QSlider;
class QPushButton;
class QMenu;
QT_END_NAMESPACE
//! [0]
class GLWidget;

class Window : public QWidget//, QMainWindow
{
    Q_OBJECT

public:
    Window();

    void createBlockLayout();
    void createBasicLayout();
    void createCloudLayout();    
    void createDrawMenu();

    QSlider *createSlider2();
public slots:
    void switchLayout(bool tim);
    void setTreeAgeSlider(int,int);

protected:
    void keyPressEvent(QKeyEvent *event);

private:
    QSlider         *createSlider();
    QPushButton     *createButton();
    QScrollArea     *scrollArea;
    QStackedLayout  *allLayouts;
    QVBoxLayout     *noSelectLayout;
    QVBoxLayout     *blockSelectLayout;
    QVBoxLayout     *cloudSelectLayout;
    QVBoxLayout     *drawMenuLayout;

    GLWidget *glWidget;
    QSlider *ageSlider;
    QSlider *girthSlider;
};
//! [0]

#endif
